## Empty and Full Numpy arrays

In [3]:
import numpy as np
  
  
#Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)

Empty Array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


## Print full Numpy array without truncation

In [6]:
import numpy as np
arr = np.arange(1001)
print(arr)

#using numpy.set_printoptions()
#syntax: numpy.set_printoptions(threshold=None, edgeitems=None, linewidth=None, suppress=None)

import sys
# Creating a 1-D array with 100 values
arr = np.arange(101)
 
# Printing all values of array without truncation
np.set_printoptions(threshold=sys.maxsize)
print(arr)

[   0    1    2 ...  998  999 1000]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


## Searching max and min element 

In [13]:
#numpy.argmax( )
import numpy as np

# Creating 5x4 array
array = np.arange(20).reshape(5, 4)
print(array)

# If no axis mentioned, then it works on the entire array
print(np.argmax(array))

# If axis=1, then it works on each row
print(np.argmax(array, axis=1))

# If axis=0, then it works on each column
print(np.argmax(array, axis=0))


array1 = np.array([
    [3, 7, 1],
    [10, 3, 2],
    [5, 6, 7]
])
print(array1)

# Sort the whole array
print(np.sort(array1, axis=None))

# Sort along each row
print(np.sort(array1, axis=1))

# Sort along each column
print(np.sort(array1, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
19
[3 3 3 3 3]
[4 4 4 4]
[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]
[ 1  2  3  3  5  6  7  7 10]
[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]
[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]


## Checkboard Pattern

In [14]:
import numpy as np

n = 8

# Create a nxn matrix filled with 0
matrix = np.zeros((n, n), dtype=int)

# fill 1 with alternate rows and column
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

# Print the checkerboard pattern
for i in range(n):
    for j in range(n):
        print(matrix[i][j], end=" ")
    print()

0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


## Multiply Two Matrices

In [15]:
import numpy as np

matrix1 = [
    [3, 4, 2],
    [5, 1, 8],
    [3, 1, 9]
]

matrix2 = [
    [3, 7, 5],
    [2, 9, 8],
    [1, 5, 8]
]

result = np.dot(matrix1, matrix2)
print(result)

[[19 67 63]
 [25 84 97]
 [20 75 95]]


## Reverser Numpy array

In [16]:
import numpy as np

array = np.array([3, 6, 7, 2, 5, 1, 8])
reversedArray = np.flipud(array)
print(reversedArray)

#Source link --> https://www.w3resource.com/python-exercises/numpy/index.php

[8 1 5 2 7 6 3]


## Multiplication of two matrixes

In [21]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)
print(result2)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


NameError: name 'result2' is not defined